CREATE TYPE week_days AS ENUM('saturday' , 'sunday', 'monday' ,'tuesday' , 'wednesday' , 'thursday' , 'friday');

CREATE TABLE IF NOT EXISTS boats (
  id int GENERATED BY DEFAULT AS identity primary key,
  name varchar(50) unique not null,
  fee numeric check(fee > 0), 
  location varchar(100) not null
);

CREATE TABLE IF NOT EXISTS sailors (
  id int GENERATED BY DEFAULT AS identity primary key,
  name varchar(50) not null,
  rating int check( rating >= 0 and rating <= 5) default 0,
  age int  check( age >= 0 and age <= 5)not null
);


CREATE TABLE IF NOT EXISTS reservers (
  sid int not null references sailors(id),
  bid int not null references boats(id),
  deposit numeric check(deposit > 0),
  day week_days not null,
  constraint sid_bid_pk primary key(sid,bid)
);

CREATE TABLE IF NOT EXISTS captains (
   sid int not null references sailors(id),
   cid int not null references sailors(id),
   start_date timestamptz default now(),
   end_data timestamptz 
);
